version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "53043:5432"

  redis:
      image: 'redis:5-alpine'
      command: redis-server
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
      env_file:
        - .env
      volumes:
        - redis:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq -q reports -c 8
    volumes:
      - ./rails_app:/rails_app
    env_file:
      - .env
    #entrypoint: sidekiq-entrypoint.sh
    depends_on:
      - db
      - redis

  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
    - 80:80
    depends_on:
      - app

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - ./rails_app:/rails_app
    #ports: - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_APP_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_APP_DATABASE_USER=${POSTGRES_USER}
    depends_on:
      - db
      - redis

volumes:
  redis:
  postgres: