version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "53043:5432"

  redis:
      image: 'redis:5-alpine'
      command: redis-server
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
      env_file:
        - .env
      volumes:
        - redis:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ./rails_app:/rails_app
    env_file:
      - .env
    #entrypoint: sidekiq-entrypoint.sh
    depends_on:
      - db
      - redis

  web:
    build:  
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
    - 80:80
    depends_on:
      - app

  app:
    image: ramar/ruby_prod:2.5
    env_file:
      - .env_production_database
      - .env_production_web
    depends_on:
      - db
      - redis

  guard:
    build: .
    volumes:
      - ./rails_app:/rails_app/
    environment:
      - RAILS_ENV=${RAILS_ENV}
    command: bundle exec guard --no-bundler-warning --no-interactions

volumes:
  redis:
  postgres: