 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/coins", type: :request do
  # Coin. As you add validations to Coin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Coin.create! valid_attributes
      get coins_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      coin = Coin.create! valid_attributes
      get coin_url(coin)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_coin_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      coin = Coin.create! valid_attributes
      get edit_coin_url(coin)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Coin" do
        expect {
          post coins_url, params: { coin: valid_attributes }
        }.to change(Coin, :count).by(1)
      end

      it "redirects to the created coin" do
        post coins_url, params: { coin: valid_attributes }
        expect(response).to redirect_to(coin_url(Coin.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Coin" do
        expect {
          post coins_url, params: { coin: invalid_attributes }
        }.to change(Coin, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post coins_url, params: { coin: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coin" do
        coin = Coin.create! valid_attributes
        patch coin_url(coin), params: { coin: new_attributes }
        coin.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the coin" do
        coin = Coin.create! valid_attributes
        patch coin_url(coin), params: { coin: new_attributes }
        coin.reload
        expect(response).to redirect_to(coin_url(coin))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        coin = Coin.create! valid_attributes
        patch coin_url(coin), params: { coin: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested coin" do
      coin = Coin.create! valid_attributes
      expect {
        delete coin_url(coin)
      }.to change(Coin, :count).by(-1)
    end

    it "redirects to the coins list" do
      coin = Coin.create! valid_attributes
      delete coin_url(coin)
      expect(response).to redirect_to(coins_url)
    end
  end
end
